### ISSUE TITLE
Add a guide for minting XRC20 tokens

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-docs#107]
1. mint a token, e.g., https://docs.near.org/docs/tutorials/near-studio/token

2. once minted, add to iotexscan/iopay via https://github.com/iotexproject/iotex-token-metadata

**Comment by simonerom** [comment]
Smart contracts intro + issue token (Studio+IoPay) + submit metadata
http://docs.iotex.io/developer/smart-contracts/introduction.html
