### ISSUE TITLE
http://docs.iotex.io/ redirects to https://docs.iotex.io/

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-docs#110]
Need a 302 or turn on HSTS, whichever is simpler.

**Comment by simonerom** [comment]
Seems that HSTS is not supported by Github Pages for custom domains yet (https://github.com/tjrobinson/tjrobinson.net/issues/5)

Not sure if this can be solved by enabling "Enforce HTTPS" the Github Pages settings for this site, and/or on the domain name provider side for docs.iotex.io. Someone who has access to the Settings for this repository can try enabling "Enforce HTTPS", on the domain side (doc.siotex.io) I don't have access either


![](https://docs.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by raullenchai** [comment]
I filed a customer support ticket for this one. Let's see!

**Comment by raullenchai** [comment]
![Screen Shot 2020-08-30 at 9 38 49 PM](https://user-images.githubusercontent.com/989846/91683352-397dcc00-eb09-11ea-8a1e-4c3e05c6e039.png)

```
curl -I http://docs.iotex.io
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://docs.iotex.io/
X-GitHub-Request-Id: B152:0A70:3705CF:3E68BD:5F4C7F1F
Content-Length: 162
Accept-Ranges: bytes
Date: Mon, 31 Aug 2020 04:40:00 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-pao17430-PAO
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1598848800.332520,VS0,VE21
Vary: Accept-Encoding
X-Fastly-Request-ID: 10dd84af8b6fc49d6c6c31efe01f6c25103e4355
```
