### ISSUE TITLE
Wrong example for `ioctl contract invoke bytecode`

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-docs#112]
<img width="856" alt="Screen Shot 2020-10-06 at 1 12 53 PM" src="https://user-images.githubusercontent.com/989846/95255032-abff5d00-07d5-11eb-953e-7cf1c247bd28.png">

**Comment by raullenchai** [comment]
https://docs.iotex.io/developer/ioctl/contract.html#invoke-smart-contract-by-function

**Comment by simonerom** [comment]
Fixed in ed2f473
