### ISSUE TITLE
Smart Contract example is wrong

### ISSUE THREAD

**Issue by Fabryprog** [iotexproject/iotex-docs#16]
In the page: https://docs.iotex.io/docs/sdk-smart-contract there is a wrong smart contract example.

Backend error is
> [ ":10:26: Error: Expected token LBrace got 'View'\n function get() public view returns (uint) {\n ^\n" ]

Into solidity 0.4.0 keyword **view** is unknown. It introduced from 0.4.16

**Comment by puncsky** [comment]
thanks for the fix
